import getpass
from huawei_e3_e5.huawei_exxxx import HuaweiModem as HuaweiModem
user = None
user = input(u'user: ')
if user == u'':
    user = None
else:
    password = getpass.getpass()
if user == None:
    gsm = HuaweiModem()
else:
    gsm = HuaweiModem(user=user, password=password)
print(gsm.all_data())
print('About to send sms')
numbers = input(u'numbers: ')
message = input(u'message: ')
gsm.send_sms(numbers, message)
print('Test properties')
print('ip', gsm.ip)
print('base_url', gsm.base_url)
print('deviceName', gsm.deviceName)
print('macAddress1', gsm.macAddress1)
print('imei', gsm.imei)
print('imsi', gsm.imsi)
print('iccid', gsm.iccid)
print('msisdn', gsm.msisdn)
print('hardwareVersion', gsm.hardwareVersion)
print('softwareVersion', gsm.softwareVersion)
print('webUIVersion', gsm.webUIVersion)
print('macAddress2', gsm.macAddress2)
print('productFamily', gsm.productFamily)
print('classify', gsm.classify)
print('supportmode', gsm.supportmode)
print('workmode', gsm.workmode)
print('serialNumber', gsm.serialNumber)
print('device_signal', gsm.device_signal)
print('monitoring_status', gsm.monitoring_status)
print('message_count', gsm.message_count)
print('device_information', gsm.imei)
print('autorun_version', gsm.autorun_version)
print('in_messages', gsm.in_messages)
print('out_messages', gsm.out_messages)
print('draft_messages', gsm.draft_messages)
print('trash_messages', gsm.trash_messages)
print('sim_inbox', gsm.sim_inbox)
print('sim_sent', gsm.sim_sent)
print('sim_draft', gsm.sim_draft)
print('mix_inbox', gsm.mix_inbox)
print('mix_sent', gsm.mix_sent)
print('mix_draft', gsm.mix_draft)
print('Test functions')
test = gsm.print_device_signal(callback=print)
test = gsm.print_monitoring_status(callback=print)
test = gsm.print_message_count(callback=print)
test = gsm.print_device_information(callback=print)
test = gsm.print_autorun_version(callback=print)
test = gsm.print_in_messages(callback=print)
test = gsm.print_out_messages(callback=print)
test = gsm.print_draft_messages(callback=print)
test = gsm.print_trash_messages(callback=print)
test = gsm.print_sim_inbox(callback=print)
test = gsm.print_sim_sent(callback=print)
test = gsm.print_sim_draft(callback=print)
test = gsm.print_mix_inbox(callback=print)
test = gsm.print_mix_sent(callback=print)
test = gsm.print_mix_draft(callback=print)
# print('reboot')
# gsm.control_reboot()

